[package]
name = "oven-host"
description = "Host system interaction infrastructure for Oven"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
ignore = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "sync", "time", "process"] }
tokio-util = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Globalization"] }

[dev-dependencies]
tempdir = { workspace = true }
